In [1]:
import pandas as pd
import numpy as np
import nltk
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
data=pd.read_csv("C:/Users/priti/OneDrive/Desktop/train.csv")

In [3]:

data.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      31962 non-null  int64 
 1   label   31962 non-null  int64 
 2   tweet   31962 non-null  object
dtypes: int64(2), object(1)
memory usage: 749.2+ KB


In [5]:
data.describe()

id         label
count  31962.000000  31962.000000
mean   15981.500000      0.070146
std     9226.778988      0.255397
min        1.000000      0.000000
25%     7991.250000      0.000000
50%    15981.500000      0.000000
75%    23971.750000      0.000000
max    31962.000000      1.000000

In [6]:
data.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

In [7]:
data=data.drop(['id'],axis=1)

In [8]:
data.head(10)

label                                              tweet
0      0   @user when a father is dysfunctional and is s...
1      0  @user @user thanks for #lyft credit i can't us...
2      0                                bihday your majesty
3      0  #model   i love u take with u all the time in ...
4      0             factsguide: society now    #motivation
5      0  [2/2] huge fan fare and big talking before the...
6      0   @user camping tomorrow @user @user @user @use...
7      0  the next school year is the year for exams.ðŸ˜...
8      0  we won!!! love the land!!! #allin #cavs #champ...
9      0   @user @user welcome here !  i'm   it's so #gr...

In [9]:
data['label'].sum()

2242

In [10]:
data['Count']=0
for i in np.arange(0,len(data.tweet)):
    data.loc[i,'Count'] = len(data.loc[i,'tweet'])

In [11]:
data.head(10)

label                                              tweet  Count
0      0   @user when a father is dysfunctional and is s...    102
1      0  @user @user thanks for #lyft credit i can't us...    122
2      0                                bihday your majesty     21
3      0  #model   i love u take with u all the time in ...     86
4      0             factsguide: society now    #motivation     39
5      0  [2/2] huge fan fare and big talking before the...    116
6      0   @user camping tomorrow @user @user @user @use...     74
7      0  the next school year is the year for exams.ðŸ˜...    143
8      0  we won!!! love the land!!! #allin #cavs #champ...     87
9      0   @user @user welcome here !  i'm   it's so #gr...     50

In [12]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

In [13]:
corpus = []
ps = PorterStemmer()

In [14]:
for i in range(0, 5572):

    # Applying Regular Expression
    
    '''
    Replace email addresses with 'emailaddr'
    Replace URLs with 'httpaddr'
    Replace money symbols with 'moneysymb'
    Replace phone numbers with 'phonenumbr'
    Replace numbers with 'numbr'
    '''
    msg = data['tweet'][i]
    msg = re.sub('\b[\w\-.]+?@\w+?\.\w{2,4}\b', 'emailaddr', data['tweet'][i])
    msg = re.sub('(http[s]?\S+)|(\w+\.[A-Za-z]{2,4}\S*)', 'httpaddr', data['tweet'][i])
    msg = re.sub('([A-Z]{3}|[A-Z]?[\$€¥])?\s?(\d{1,3}((,\d{1,3})+)?(.\d{1,3})?(.\d{1,3})?(,\d{1,3})?)', 'moneysymb', data['tweet'][i])
    msg = re.sub('\b(\+\d{1,2}\s)?\d?[\-(.]?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\b', 'phonenumbr',data['tweet'][i])
    msg = re.sub('\d+(\.\d+)?', 'numbr', data['tweet'][i])
    
    ''' Remove all punctuations '''
    msg = re.sub('[^\w\d\s]', ' ', data['tweet'][i])
    
    if i<2:
        print("\t\t\t\t MESSAGE ", i)
    
    if i<2:
        print("\n After Regular Expression - Message ", i, " : ", msg)
    
    # Each word to lower case
    msg = msg.lower()    
    if i<2:
        print("\n Lower case Message ", i, " : ", msg)
    
    # Splitting words to Tokenize
    msg = msg.split()    
    if i<2:
        print("\n After Splitting - Message ", i, " : ", msg)
    
    # Stemming with PorterStemmer handling Stop Words
    msg = [ps.stem(word) for word in msg if not word in set(stopwords.words('english'))]
    if i<2:
        print("\n After Stemming - Message ", i, " : ", msg)
    
    # preparing Messages with Remaining Tokens
    msg = ' '.join(msg)
    if i<2:
        print("\n Final Prepared - Message ", i, " : ", msg, "\n\n")
    
    # Preparing WordVector Corpus
    corpus.append(msg)

				 MESSAGE  0

 After Regular Expression - Message  0  :    user when a father is dysfunctional and is so selfish he drags his kids into his dysfunction     run

 Lower case Message  0  :    user when a father is dysfunctional and is so selfish he drags his kids into his dysfunction     run

 After Splitting - Message  0  :  ['user', 'when', 'a', 'father', 'is', 'dysfunctional', 'and', 'is', 'so', 'selfish', 'he', 'drags', 'his', 'kids', 'into', 'his', 'dysfunction', 'run']

 After Stemming - Message  0  :  ['user', 'father', 'dysfunct', 'selfish', 'drag', 'kid', 'dysfunct', 'run']

 Final Prepared - Message  0  :  user father dysfunct selfish drag kid dysfunct run 


				 MESSAGE  1

 After Regular Expression - Message  1  :   user  user thanks for  lyft credit i can t use cause they don t offer wheelchair vans in pdx      disapointed  getthanked

 Lower case Message  1  :   user  user thanks for  lyft credit i can t use cause they don t offer wheelchair vans in pdx      disapointed

In [15]:
cv=CountVectorizer()


In [16]:
x=cv.fit_transform(corpus).toarray()

In [17]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
y=data.iloc[0:5572,0:1]

In [19]:
y.head()

label
0      0
1      0
2      0
3      0
4      0

In [20]:
le = LabelEncoder()
y = le.fit_transform(y)

print(y[0])
print(y[1])

0
0


C:\Users\priti\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [21]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y,test_size= 0.20, random_state = 0)

In [22]:
bayes_classifier = GaussianNB()
bayes_classifier.fit(xtrain, ytrain)

GaussianNB()

In [23]:
y_pred = bayes_classifier.predict(xtest)

In [24]:
cm = confusion_matrix(ytest, y_pred)
cm

array([[971,  60],
       [ 52,  32]], dtype=int64)

In [25]:
print ("Accuracy : %0.5f \n\n" % accuracy_score(ytest, bayes_classifier.predict(xtest)))
print (classification_report(ytest, bayes_classifier.predict(xtest)))

Accuracy : 0.89955 


              precision    recall  f1-score   support

           0       0.95      0.94      0.95      1031
           1       0.35      0.38      0.36        84

    accuracy                           0.90      1115
   macro avg       0.65      0.66      0.65      1115
weighted avg       0.90      0.90      0.90      1115



In [26]:
dt = DecisionTreeClassifier(random_state=50)
dt.fit(xtrain, ytrain)

DecisionTreeClassifier(random_state=50)

In [27]:
y_pred_dt = dt.predict(xtest)

In [28]:
cm = confusion_matrix(ytest, y_pred_dt)

print(cm)

[[1003   28]
 [  37   47]]


In [29]:
print ("Accuracy : %0.5f \n\n" % accuracy_score(ytest, dt.predict(xtest)))
print (classification_report(ytest, dt.predict(xtest)))

Accuracy : 0.94170 


              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1031
           1       0.63      0.56      0.59        84

    accuracy                           0.94      1115
   macro avg       0.80      0.77      0.78      1115
weighted avg       0.94      0.94      0.94      1115



In [30]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
rf=RandomForestClassifier(n_estimators=50, criterion = 'entropy', random_state = 0)

In [37]:
rf.fit(xtrain,ytrain)

RandomForestClassifier(criterion='entropy', n_estimators=50, random_state=0)

In [38]:
ypred=rf.predict(xtest)

In [39]:
cm = confusion_matrix(ytest, ypred)

print(cm)

[[1031    0]
 [  68   16]]


In [40]:
print ("Accuracy : %0.5f \n\n" % accuracy_score(ytest, rf.predict(xtest)))
print (classification_report(ytest, dt.predict(xtest)))

Accuracy : 0.93901 


              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1031
           1       0.63      0.56      0.59        84

    accuracy                           0.94      1115
   macro avg       0.80      0.77      0.78      1115
weighted avg       0.94      0.94      0.94      1115

